# ???, ?? ????, ????, ???? ????
spring.profiles.include=api
# application.properties \uD30C\uC77C\uC740 \uD56D\uC0C1 resources \uBC14\uB85C \uC544\uB798 \uB9CC\uB4E0\uB2E4.
# \uBAA9\uC801: \uC2A4\uD504\uB9C1 \uC11C\uBC84\uAC00 \uC2E4\uD589\uB420 \uB54C \uC124\uC815\uC744 \uB85C\uB529\uD558\uB294 \uD30C\uC77C
# \uCC38\uACE0 : \uC0C1\uB2E8\uBA54\uB274 -> \uC124\uC815 -> \uD30C\uC77C \uC778\uCF54\uB529 \uBA54\uB274 -> \uD504\uB85C\uD37C\uD2F0 \uD30C\uC77C\uC758 \uB300\uD55C \uB514\uD3F4\uD2B8 \uC778\uCF54\uB529 : UTF-8 \uBCC0\uACBD


# 1. \uB0B4\uC7A5 AWS PORT(\uD504\uB85C\uADF8\uB7A8 \uC2DD\uBCC4\uBC88\uD638) \uBC88\uD638 \uBCC0\uACBD , \uAE30\uBCF8\uAC12\uC740 8080 \uC218\uC815 \uAC00\uB2A5
server.port = 8080

# 2. DAO \uAC00 \uC544\uB2CC \uD504\uB85C\uD37C\uD2F0 \uD30C\uC77C\uC5D0\uC11C DB \uC5F0\uB3D9 \uAC00\uB2A5\uD558\uB2E4. JDBC
# 2-1 \uC5F0\uB3D9\uD560 db\uC11C\uBC84\uC758 \uC8FC\uC18C
spring.datasource.url = jdbc:mysql://localhost:3306/hamoyeah
# 2-2 \uC5F0\uB3D9\uD560 db\uC11C\uBC84\uC758 \uACC4\uC815/\uBE44\uBC00\uBC88\uD638  \uB744\uC5B4\uC4F0\uAE30 \uC8FC\uC758
spring.datasource.username = root
spring.datasource.password = 1234


#2-3 Entity \uD14C\uC774\uBE14 \uC0DD\uC131, DDL : sql \uC815\uC758\uC5B4
# create : \uC11C\uBC84\uC2E4\uD589\uD560\uB54C\uB9C8\uB2E4 \uC0AD\uC81C\uD6C4 \uC0DD\uC131
# update : \uC11C\uBC84\uC2E4\uD589\uD560\uB54C\uB9C8\uB2E4 \uC874\uC7AC\uD558\uBA74 \uC218\uC815 \uC874\uC7AC\uD558\uC9C0 \uC54A\uC73C\uBA74 \uC0DD\uC131
# none : \uC0AC\uC6A9\uC548\uD568
spring.jpa.hibernate.ddl-auto=update

# 2-4 \uCF58\uC194\uCC3D\uC5D0 \uC2E4\uD589\uB41C sql \uD45C\uC2DC
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# sql \uB0B4 \uB9E4\uAC1C\uBCC0\uC218 \uAC12\uB4E4\uC744 \uD45C\uC2DC
logging.level.org.hibernate.jdbc.bind = TRACE
logging.level.org.hibernate.sql = DEBUG

# 2-5 \uC11C\uBC84\uB97C \uC2E4\uD589 \uD560\uB54C SQL \uD30C\uC77C \uC2E4\uD589 *\uAC1C\uBC1C\uB2E8\uACC4* , always ,none
#spring.sql.init.mode = always
# 2-6 \uC11C\uBC84 \uC2E4\uD589 \uD560\uB54C classpath(resources\uD3F4\uB354) \uC774\uD558\uC5D0 data.sql \uD30C\uC77C \uACBD\uB85C \uC9C0\uC815
spring.sql.init.data-locations=classpath:/sql/data.sql
# 2-7 \uC11C\uBC84 \uC2E4\uD589 \uD560\uB54C JPA\uAC00 \uCD08\uAE30\uD654 \uD30C\uC77C \uC2E4\uD589
spring.jpa.defer-datasource-initialization=true


# 3 \uC5C5\uB85C\uB4DC \uD30C\uC77C \uCD5C\uB300 \uC6A9\uB7C9 \uC81C\uD55C \uC124\uC815, \uAE30\uBCF8\uAC12 1MB = 1024byte
# 3-1 : \uD30C\uC77C\uB9C8\uB2E4\uC758 \uC6A9\uB7C9 \uC81C\uD55C
spring.servlet.multipart.max-file-size=10MB
# 3-2 : \uD55C\uBC88 \uC694\uCCAD\uC5D0 \uC5EC\uB7EC\uAC1C \uD30C\uC77C \uD55C\uBC88\uC5D0 \uC804\uC1A1 \uD588\uC744\uB54C \uCD5C\uB300 \uC6A9\uB7C9
spring.servlet.multipart.max-request-size= 100MB
#2-8 \uC774\uBA54\uC77C \uC778\uC99D
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yexxjx@gmail.com
spring.mail.password=ewjvlcztxxhizogl

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.debug=true

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000