# ???, ?? ????, ????, ???? ????
spring.profiles.include=api
# application.properties ??? ?? resource?? ?? ?? ???.
# ?? : ??? ??? ??? ? ??? ???? ??
# ????? # ????.
# ?? : ???? -> ?? -> '???'?? -> ?? ??? ?? ??
#  ???? ??? ?? ??? ??? : UTF-8 ??

# 1. ?? AWS PORT(????????) ?? ?? , ???? 8080 ?? ?? ??.
server.port = 8080

# 2. DAO ? ?? ???? ???? DB?? ????. JDBC
# 2-1 ??? db??? ??
spring.datasource.url=jdbc:mysql://localhost:3306/hamoyeah

# 2-2 ??? db??? ??/???? , ???? ??
spring.datasource.username=root
spring.datasource.password=1234
# 2-3 Entity ??? ??/??, DDL: sql???
# create: ?? ??? ??? ?? ? ??
# update: ?? ??? ??? ???? ??, ???? ??? ??
# none: ????
spring.jpa.hibernate.ddl-auto=create

# 2-4 ???? ???? ??? sql ?? *????* ???(???) *??/?? ?? ???? ???*
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# SQL ? ???? ??? ?? * ??/?? ? ????(????) ?? ?? ??
logging.level.org.hibernate.orm.jdbc.bind = TRACE
logging.level.org.hibernate.sql = DEBUG

# 2-5 ?? ?? ?? SQL ?? ?? *????* , always,none *??/?? ?? ???? ???*
spring.sql.init.mode = always
# 2-6 ?? ?? ?? classpath(resources??) ?? ? data.sql ?? ?? ??
spring.sql.init.data-locations=classpath:/sql/data.sql
# 2-7 ?? ?? ?? JPA? ??? ?? ??
spring.jpa.defer-datasource-initialization = true